name: Complie

on:
  push:
    branches: [ "main" ]
    tags:
      - 'test'
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: sudo apt install clang -y
    - name: make server (4 test)
      run: clang++ server.cpp -o client -pthread -latomic
    - name: make client (4 test)
      run: clang++ client.cpp -o client -pthread -latomic
    - name: creating zip
      run: zip -r v0.1.zip server.cpp client.cpp
    - name: Create a Release in a GitHub Action
      id: create_release
      uses: comnoco/create-release-action@v2.0.5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: 0.1
        release_name: Hello World! v0.1
        draft: false
    - name: Uploading...
      uses: softprops/action-gh-release@v2.2.2
      if: github.ref_type == '0.1'
      with:
        files: v0.1.zip   
      
