name: Complie

on:
  push:
    branches: [ "main" ]
    tags:
      - 'test'
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: sudo apt install clang -y
    - name: make server
      run: clang++ server.cpp -o client -pthread -latomic
    - name: make client
      run: clang++ client.cpp -o client -pthread -latomic
    - name: Create a Release in a GitHub Action
      id: create_release
      uses: comnoco/create-release-action@v2.0.5
      run: zip -r test.zip server client
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: true
      
