name: Publish to npm

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org/'

      - name: Configure Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install dependencies
        run: npm install

      - name: Version update
        run: |
          npm version patch --no-git-tag-version
          git add package.json package-lock.json
          git commit -m "chore: bump version [skip ci]"
          git push

      - name: Publish to npm
        run: npm publish --always-auth=false
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
